### PR TITLE
unifies target name

### PR DESCRIPTION
**Pull request by ryanmrichard**
@jwaldrop107  see if this fixes your problem. The target name should now always be whatever is specified as the dependency's name (the first argument to `cpp_find_or_build_dependency`). In what appears to be pure dumb luck, this change should be non-breaking for utilities, SDE, and libchemist.

### CODE REVIEW

**Comment by jwaldrop107** [comment]
Currently, I'm getting the following error when I try it, 
`CMake Error at cmake-build-debug/_deps/cpp-src/cmake/cpp/dependency/dependency_class.cmake:109 (add_library):
  add_library cannot create ALIAS target "Catch2" because target
  "Catch2::Catch2" is imported but not globally visible.`

**Comment by ryanmrichard** [comment]
sigh. It looks like it is going to have to always be the name of the find target, which is going to be breaking.

**Comment by jwaldrop107** [comment]
The changes have it throwing the following error with utilities and some others: `CMake Error at cmake-build-debug/_deps/cpp-src/cmake/cpp/user_api/find_or_build_dependency.cmake:31 (add_library):
  The target name "" is reserved or not valid for certain CMake features,
  such as generator expressions, and may result in undefined behavior.`

**Comment by ryanmrichard** [comment]
@jwaldrop107 the PR isn't read to be tested yet. I'll let you know.

**Comment by ryanmrichard** [comment]
@jwaldrop107 use the target_unify branch of libchemist and add a `FIND_TARGET nwx::libchemist` to the `cpp_find_or_build_dependency(libchemist...)` line in your CMakeLists.txt

**Comment by jwaldrop107** [comment]
That seems to be working fine.

**Comment by ryanmrichard** [comment]
@jwaldrop107 now try it with all master branches and see if it still works

**Comment by jwaldrop107** [comment]
@ryanmrichard, Everything still looks good.

**Pull request merged**
